server:
  port: ${PORT:8081}
spring:
  application:
    name: oms-order-manager
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:54321/order-db}
    username: ${ORDER_DB_USER:order-manager-user}
    password: ${ORDER_DB_PASSWORD:bha@ycb3czy5gfn-YQN}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:oms-order-manager}
      topic:
        oms-order-import-topic: ${OMS-ORDER-IMPORT-TOPIC:oms-order-import-topic}
        
    producer:
      topic:
        oms-order-stock-topic: ${OMS-ORDER-STOCK-TOPIC:oms-order-stock-topic}
        oms-order-notification-topic: ${OMS-ORDER-NOTIFICATION-TOPIC:oms-order-notification-topic}
  
  

